// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/srgjo27/scalable_ticket/internal/core/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// BookingRepository is an autogenerated mock type for the BookingRepository type
type BookingRepository struct {
	mock.Mock
}

// CancelBooking provides a mock function with given fields: ctx, bookingID
func (_m *BookingRepository) CancelBooking(ctx context.Context, bookingID uuid.UUID) error {
	ret := _m.Called(ctx, bookingID)

	if len(ret) == 0 {
		panic("no return value specified for CancelBooking")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, bookingID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateBooking provides a mock function with given fields: ctx, booking
func (_m *BookingRepository) CreateBooking(ctx context.Context, booking *domain.Booking) error {
	ret := _m.Called(ctx, booking)

	if len(ret) == 0 {
		panic("no return value specified for CreateBooking")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Booking) error); ok {
		r0 = rf(ctx, booking)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetExpiredBookings provides a mock function with given fields: ctx
func (_m *BookingRepository) GetExpiredBookings(ctx context.Context) ([]uuid.UUID, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetExpiredBookings")
	}

	var r0 []uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]uuid.UUID, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []uuid.UUID); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatus provides a mock function with given fields: ctx, bookingID, status
func (_m *BookingRepository) UpdateStatus(ctx context.Context, bookingID uuid.UUID, status domain.BookingStatus) error {
	ret := _m.Called(ctx, bookingID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.BookingStatus) error); ok {
		r0 = rf(ctx, bookingID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBookingRepository creates a new instance of BookingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookingRepository {
	mock := &BookingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
