// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/srgjo27/scalable_ticket/internal/core/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// SeatRepository is an autogenerated mock type for the SeatRepository type
type SeatRepository struct {
	mock.Mock
}

// GetAvailableSeatsByEvent provides a mock function with given fields: ctx, eventID
func (_m *SeatRepository) GetAvailableSeatsByEvent(ctx context.Context, eventID uuid.UUID) ([]domain.Seat, error) {
	ret := _m.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for GetAvailableSeatsByEvent")
	}

	var r0 []domain.Seat
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]domain.Seat, error)); ok {
		return rf(ctx, eventID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []domain.Seat); ok {
		r0 = rf(ctx, eventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Seat)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, seatID
func (_m *SeatRepository) GetByID(ctx context.Context, seatID uuid.UUID) (*domain.Seat, error) {
	ret := _m.Called(ctx, seatID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Seat
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Seat, error)); ok {
		return rf(ctx, seatID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Seat); ok {
		r0 = rf(ctx, seatID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Seat)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, seatID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LockSeat provides a mock function with given fields: ctx, seatID, bookingID, currentVersion
func (_m *SeatRepository) LockSeat(ctx context.Context, seatID uuid.UUID, bookingID uuid.UUID, currentVersion int) error {
	ret := _m.Called(ctx, seatID, bookingID, currentVersion)

	if len(ret) == 0 {
		panic("no return value specified for LockSeat")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int) error); ok {
		r0 = rf(ctx, seatID, bookingID, currentVersion)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UnlockSeat provides a mock function with given fields: ctx, seatID
func (_m *SeatRepository) UnlockSeat(ctx context.Context, seatID uuid.UUID) error {
	ret := _m.Called(ctx, seatID)

	if len(ret) == 0 {
		panic("no return value specified for UnlockSeat")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, seatID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSeatRepository creates a new instance of SeatRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSeatRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SeatRepository {
	mock := &SeatRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
